### ISSUE TITLE
Valores no Modificables en Actividad Simulador

### ISSUE THREAD

**Issue by Nandotec** [jemsz95/tiro-parabolico#2]
Erroneamente declaré los valores númericos asociados al tiempo, alcance y altura máxima como EditTexts en lugar de TextViews, ademas parece haber una falla que hace que no se pueda escribir valores y que se vean desplegados en la linea, por lo que se debe de reparar esa falla tambien.

**Comment by JorgeRubio96** [comment]
Ya se soluciono el problema relacionado con la parte de la interfaz (XML)
